language:
  - node_js

node_js:
  - 'node'
  - '6'
  - '4'


script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: coverage
      script: echo "run coverage"
    - stage: npm release
      node_js: 6
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        script: echo "deploy"
        on:
          branch: master
