language:
  - node_js

node_js:
  - 'node'
  - '6'
  - '4'

env:
  - STEP=lint
  - STEP=test
  - STEP=cover

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: coverage
      script: echo "run coverage"
      node_js:
        - 8
        - 6
        - 4
    - stage: npm release
      node_js: 6
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        script: echo "deploy"
        on:
          branch: master
